[package]
name = "project"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.1"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.43.0", features = ["full"] }

[dev-dependencies]
serde_json = "1.0"
tower = { version = "0.5", features = ["util"] }
